namespace: "softasap"
name: "swarm_box"
description: Configures swarm cluster including masters, managers and worker nodes
version: 0.7.0
readme: "Readme.md"
authors:
    - "Vyacheslav Voronenko"
dependencies:
license:
    - "MIT"
tags:
    - softasap
repository: "https://github.com/oops-to-devops/swarm-box"
documentation: "https://github.com/oops-to-devops/swarm-box/blob/master/README.md"
homepage: "https://www.softasap.com"
issues: "https://github.com/orgs/oops-to-devops/projects/1"
